version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    image: asia.gcr.io/testing-190408-237002/rails_puma_gke_sample/app:latest
    # image: test:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
      DB_HOST: db
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  web:
    image: asia.gcr.io/testing-190408-237002/rails_puma_gke_sample/web:latest
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 9000:8080
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
