apiVersion: v1
kind: Service
metadata:
  # name で名前解決できる
  name: dbserver-service

spec:
  # クラスタ上に公開
  type: ClusterIP
  selector:
    # これにマッチした pod に流す
    app: rails
    server: db
  ports:
    - name: mysql
      port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: rails

spec:
  replicas: 1
  selector:
    matchLabels:
      server: db
  template:
    metadata:
      labels:
        app: rails
        server: db
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Tokyo
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
