apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ryo-murakami@two2.jp
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ssl-testing
  namespace: default
spec:
  secretName: ssl-testing-tls
  issuerRef:
    name: letsencrypt
  commonName: ssl-testing.work
  dnsNames:
  - ssl-testing.work
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ssl-testing.work
    # - http01:
    #     ingress: my-ingress
    #   domains:
    #   - staging.ssl-testing.work
  