apiVersion: v1
data:
  password: 6MCm7eLlpHxOJlbCwD6T1LqfkhahDAdlKzGNQ0syjBL7pIYtpIQTke3JnK2PsGO9.m61g8EjpyNOuUIsk.9OqIhXN3nF10Z7F5Yn5n5g==
  rails_master_key: uBELgJCO7fWFDyEUtqbARKpWZZg9aA9A1enzSKdvmCECRjYfTwhXJZGpw7ZVdIiR.3zVGdfSkFAAMgV8d.Y0/M8meAicvTuG+3AtPDlQ==
  rootpass: NKEFviBTAs5bAmu5+cv44epUMQEKUBORvPIdPKHOy/m+iHyoKlxpbz4xulXM8A5I.dxryN+7UgatjjS7M.iqZtbZ4x4Uv+0GAUErsMRQ==
  username: XrInNkpJ+8+h98zyTf63+VEgKXwnZOqMU8xLtof8cHPug5Co47XznV7OHULEJCf8.II6mrhbYTVo4nupf.AOz7iaurhTFpIJQIx0vn2A==
kind: Secret
metadata:
  name: secret
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/testing-190408-237002/locations/asia-northeast1/keyRings/sample_gke_keyring/cryptoKeys/sample_gke_key:CiQAu0x1o/OnPtojWQOXD+i6okXftsKoX5ijZD3b/By+fo7IxPASSQDjtNUCxsaSggFb52S1u1OeMx0pd7bZU2QSIvMIHEE31+4AdtQGzwmowX16fuQtPV3REaQjewjPO1+iYuqGM2kRPjEgFfh3i+M=
# kubesec:mac:fpHDCqZt4+WNMUaF.BrdEdde5NtWaWhB2R95Fzw==
